import { Prisma, PrismaClient } from "@prisma/client";

import { deliveryZonesData } from "./ensure-delivery-zones";

const prisma = new PrismaClient();

type ProductSeed = {
    name: string;
    slug: string;
    description: string;
    composition: string;
    price: number;
    weight: number;
    image: string;
    categorySlug: "pizza" | "sushi" | "shawarma" | "drinks" | "snacks";
};

function unsplash(photoId: string): string {
    return `https://images.unsplash.com/photo-${photoId}?w=800&q=80`;
}

const PIZZA_IMAGES = [
    "1513104890138-7c749659a591",
    "1574071318508-1cdbab67150d",
    "1565299624946-b28f40a0ae38",
    "1593560707562-0cc2d55e1b63",
    "1628840042765-356cda074004",
    "1513104890138-7c749659a591",
    "1574071318508-1cdbab67150d",
    "1565299624946-b28f40a0ae38",
    "1593560707562-0cc2d55e1b63",
    "1628840042765-356cda074004",
    "1513104890138-7c749659a591",
    "1574071318508-1cdbab67150d",
    "1565299624946-b28f40a0ae38",
    "1593560707562-0cc2d55e1b63",
    "1628840042765-356cda074004",
    "1513104890138-7c749659a591",
    "1574071318508-1cdbab67150d",
    "1565299624946-b28f40a0ae38",
    "1593560707562-0cc2d55e1b63",
    "1628840042765-356cda074004",
];

const SUSHI_IMAGES = [
    "1579584425558-c946ce208915",
    "1617195738942-64354f59c7a5",
    "1611145794564-f1e5f3f3e456",
    "1553621042-f6e147245754",
    "1579584425558-c946ce208915",
    "1617195738942-64354f59c7a5",
    "1611145794564-f1e5f3f3e456",
    "1553621042-f6e147245754",
    "1579584425558-c946ce208915",
    "1617195738942-64354f59c7a5",
    "1611145794564-f1e5f3f3e456",
    "1553621042-f6e147245754",
    "1579584425558-c946ce208915",
    "1617195738942-64354f59c7a5",
    "1611145794564-f1e5f3f3e456",
    "1553621042-f6e147245754",
    "1579584425558-c946ce208915",
    "1617195738942-64354f59c7a5",
    "1611145794564-f1e5f3f3e456",
    "1553621042-f6e147245754",
];

const SHAWARMA_IMAGES = [
    "1529006557810-274b1b48f73e",
    "1626700051175-6818013e1d4f",
    "1599974576235-30ac3adb2752",
    "1529006557810-274b1b48f73e",
    "1626700051175-6818013e1d4f",
    "1599974576235-30ac3adb2752",
    "1529006557810-274b1b48f73e",
    "1626700051175-6818013e1d4f",
    "1599974576235-30ac3adb2752",
    "1529006557810-274b1b48f73e",
    "1626700051175-6818013e1d4f",
    "1599974576235-30ac3adb2752",
    "1529006557810-274b1b48f73e",
    "1626700051175-6818013e1d4f",
    "1599974576235-30ac3adb2752",
    "1529006557810-274b1b48f73e",
    "1626700051175-6818013e1d4f",
    "1599974576235-30ac3adb2752",
    "1529006557810-274b1b48f73e",
    "1626700051175-6818013e1d4f",
];

const DRINKS_IMAGES = [
    "1544145945-f54f6a0c36a2",
    "1629203851122-3726ecdf080e",
    "1437750769467-756a06476712",
    "1544145945-f54f6a0c36a2",
    "1629203851122-3726ecdf080e",
    "1437750769467-756a06476712",
    "1544145945-f54f6a0c36a2",
    "1629203851122-3726ecdf080e",
    "1437750769467-756a06476712",
    "1544145945-f54f6a0c36a2",
    "1629203851122-3726ecdf080e",
    "1437750769467-756a06476712",
    "1544145945-f54f6a0c36a2",
    "1629203851122-3726ecdf080e",
    "1437750769467-756a06476712",
    "1544145945-f54f6a0c36a2",
    "1629203851122-3726ecdf080e",
    "1437750769467-756a06476712",
    "1544145945-f54f6a0c36a2",
    "1629203851122-3726ecdf080e",
];

const SNACKS_IMAGES = [
    "1573080496219-bb08000f1a82",
    "1563245372-f21724c46173",
    "1626082897022-fc099e2a282d",
    "1573080496219-bb08000f1a82",
    "1563245372-f21724c46173",
    "1626082897022-fc099e2a282d",
    "1573080496219-bb08000f1a82",
    "1563245372-f21724c46173",
    "1626082897022-fc099e2a282d",
    "1573080496219-bb08000f1a82",
    "1563245372-f21724c46173",
    "1626082897022-fc099e2a282d",
    "1573080496219-bb08000f1a82",
    "1563245372-f21724c46173",
    "1626082897022-fc099e2a282d",
    "1573080496219-bb08000f1a82",
    "1563245372-f21724c46173",
    "1626082897022-fc099e2a282d",
    "1573080496219-bb08000f1a82",
    "1563245372-f21724c46173",
];

const productsData: ProductSeed[] = [
    // ─── Пицца (20) ───────────────────────────────────────────────────────────
    {
        name: "Пепперони",
        slug: "pepperoni",
        description: "Классика с острой колбасой и расплавленной моцареллой. Хрустящие края, сочная начинка.",
        composition: "Тесто, томатный соус, моцарелла, пепперони, орегано",
        price: 5800,
        weight: 520,
        image: unsplash(PIZZA_IMAGES[0]),
        categorySlug: "pizza",
    },
    {
        name: "Маргарита",
        slug: "margarita",
        description: "Лёгкая неаполитанская пицца с базиликом и свежими томатами. Идеальна для любого настроения.",
        composition: "Тесто, томатный соус, моцарелла, свежий базилик, оливковое масло",
        price: 5200,
        weight: 480,
        image: unsplash(PIZZA_IMAGES[1]),
        categorySlug: "pizza",
    },
    {
        name: "Четыре сыра",
        slug: "chetyre-syra",
        description: "Сливочная основа и богатый микс сыров — для настоящих гурманов.",
        composition: "Тесто, сливочный соус, моцарелла, горгонзола, пармезан, чеддер",
        price: 6500,
        weight: 500,
        image: unsplash(PIZZA_IMAGES[2]),
        categorySlug: "pizza",
    },
    {
        name: "Гавайская",
        slug: "gavayskaya",
        description: "Сладкий ананас и нежная ветчина в мягком тесте. Любимый вариант для семейного ужина.",
        composition: "Тесто, томатный соус, моцарелла, ветчина, ананас",
        price: 5400,
        weight: 510,
        image: unsplash(PIZZA_IMAGES[3]),
        categorySlug: "pizza",
    },
    {
        name: "Мясная",
        slug: "myasnaya",
        description: "Щедрая начинка из говядины, бекона и курицы. Сытная и ароматная.",
        composition: "Тесто, томатный соус, моцарелла, говядина, бекон, курица, лук",
        price: 7200,
        weight: 580,
        image: unsplash(PIZZA_IMAGES[4]),
        categorySlug: "pizza",
    },
    {
        name: "Барбекю",
        slug: "bbq-pizza",
        description: "Копчёный соус BBQ, курица и хрустящий лук. Яркий вкус американской классики.",
        composition: "Тесто, соус BBQ, моцарелла, куриное филе, лук, кукуруза",
        price: 6100,
        weight: 530,
        image: unsplash(PIZZA_IMAGES[5]),
        categorySlug: "pizza",
    },
    {
        name: "Грибная",
        slug: "gribnaya",
        description: "Шампиньоны, сливки и пармезан — нежная пицца без лишней тяжести.",
        composition: "Тесто, сливочный соус, моцарелла, шампиньоны, пармезан, чеснок",
        price: 5600,
        weight: 490,
        image: unsplash(PIZZA_IMAGES[6]),
        categorySlug: "pizza",
    },
    {
        name: "Карбонара",
        slug: "karbonara-pizza",
        description: "Вдохновлена пастой: бекон, яйцо и сливочный соус на хрустящем тесте.",
        composition: "Тесто, сливочный соус, моцарелла, бекон, яичный соус, пармезан",
        price: 6800,
        weight: 540,
        image: unsplash(PIZZA_IMAGES[7]),
        categorySlug: "pizza",
    },
    {
        name: "Диабло",
        slug: "diablo",
        description: "Острая пицца с перцем чили и пепперони. Для тех, кто любит жар.",
        composition: "Тесто, томатный соус, моцарелла, пепперони, халапеньо, перец чили",
        price: 5900,
        weight: 515,
        image: unsplash(PIZZA_IMAGES[8]),
        categorySlug: "pizza",
    },
    {
        name: "Сырная",
        slug: "syrnaya",
        description: "Двойная моцарелла и сливочный соус — максимум сыра в каждом кусочке.",
        composition: "Тесто, сливочный соус, моцарелла, сыр чеддер, пармезан",
        price: 5500,
        weight: 470,
        image: unsplash(PIZZA_IMAGES[9]),
        categorySlug: "pizza",
    },
    {
        name: "Овощная",
        slug: "ovoshchnaya-pizza",
        description: "Свежие овощи на тонком тесте — лёгкий и сбалансированный вариант.",
        composition: "Тесто, томатный соус, моцарелла, перец, томаты, баклажан, кабачок, оливки",
        price: 4800,
        weight: 460,
        image: unsplash(PIZZA_IMAGES[10]),
        categorySlug: "pizza",
    },
    {
        name: "Три мяса",
        slug: "tri-myasa",
        description: "Говядина, свинина и курица — максимально сытная пицца для большой компании.",
        composition: "Тесто, томатный соус, моцарелла, говядина, свинина, курица, лук",
        price: 7500,
        weight: 590,
        image: unsplash(PIZZA_IMAGES[11]),
        categorySlug: "pizza",
    },
    {
        name: "Чикен",
        slug: "chicken-pizza",
        description: "Нежное куриное филе с грибами и сливочным соусом. Мягкий, домашний вкус.",
        composition: "Тесто, сливочный соус, моцарелла, куриное филе, шампиньоны",
        price: 5700,
        weight: 505,
        image: unsplash(PIZZA_IMAGES[12]),
        categorySlug: "pizza",
    },
    {
        name: "Парма",
        slug: "parma",
        description: "Пармская ветчина, руккола и пармезан — итальянская элегантность на тарелке.",
        composition: "Тесто, томатный соус, моцарелла, пармская ветчина, руккола, пармезан",
        price: 6900,
        weight: 495,
        image: unsplash(PIZZA_IMAGES[13]),
        categorySlug: "pizza",
    },
    {
        name: "Неаполитанская",
        slug: "neapolitanskaya",
        description: "Тонкое тесто, томаты Сан-Мarzano и свежий базилик по классическому рецепту.",
        composition: "Тесто, томатный соус, моцарелла, томаты, базилик, оливковое масло",
        price: 5300,
        weight: 475,
        image: unsplash(PIZZA_IMAGES[14]),
        categorySlug: "pizza",
    },
    {
        name: "Болоньезе",
        slug: "boloneze-pizza",
        description: "Сытный мясной соус болоньезе и расплавленный сыр — как любимая паста, но на пицце.",
        composition: "Тесто, томатный соус, моцарелла, фарш говяжий, лук, морковь, базилик",
        price: 6000,
        weight: 525,
        image: unsplash(PIZZA_IMAGES[15]),
        categorySlug: "pizza",
    },
    {
        name: "Охотничья",
        slug: "okhotnichya",
        description: "Охотничьи колбаски, грибы и маринованные огурчики — насыщенный деревенский вкус.",
        composition: "Тесто, томатный соус, моцарелла, охотничьи колбаски, шампиньоны, огурцы",
        price: 6400,
        weight: 535,
        image: unsplash(PIZZA_IMAGES[16]),
        categorySlug: "pizza",
    },
    {
        name: "Тунец",
        slug: "tunec-pizza",
        description: "Нежный тунец с красным луком и каперсами — свежий морской акцент.",
        composition: "Тесто, томатный соус, моцарелла, тунец, красный лук, каперсы, оливки",
        price: 5800,
        weight: 485,
        image: unsplash(PIZZA_IMAGES[17]),
        categorySlug: "pizza",
    },
    {
        name: "Баварская",
        slug: "bavarskaya",
        description: "Сливочный соус, бекон и картофель — сытная пицца в баварском стиле.",
        composition: "Тесто, сливочный соус, моцарелла, бекон, картофель, лук, зелень",
        price: 6200,
        weight: 545,
        image: unsplash(PIZZA_IMAGES[18]),
        categorySlug: "pizza",
    },
    {
        name: "Тартюфо",
        slug: "tartufo",
        description: "Трюфельное масло, грибы и пармезан — изысканная пицца для особого вечера.",
        composition: "Тесто, сливочный соус, моцарелла, шампиньоны, трюфельное масло, пармезан",
        price: 7800,
        weight: 500,
        image: unsplash(PIZZA_IMAGES[19]),
        categorySlug: "pizza",
    },

    // ─── Суши и роллы (20) ────────────────────────────────────────────────────
    {
        name: "Филадельфия",
        slug: "filadelfiya",
        description: "Легендарный ролл с лососем и сливочным сыром. Нежный, сбалансированный, без лишней остроты.",
        composition: "Рис, нори, лосось, сливочный сыр, огурец",
        price: 4900,
        weight: 240,
        image: unsplash(SUSHI_IMAGES[0]),
        categorySlug: "sushi",
    },
    {
        name: "Калифорния",
        slug: "kaliforniya",
        description: "Краб, авокадо и икра тобико — яркий ролл с хрустящей текстурой.",
        composition: "Рис, нори, краб, авокадо, огурец, икра тобико",
        price: 4500,
        weight: 220,
        image: unsplash(SUSHI_IMAGES[1]),
        categorySlug: "sushi",
    },
    {
        name: "Дракон",
        slug: "drakon",
        description: "Запечённый ролл с угрём и соусом унаги. Сладковатый, насыщенный вкус.",
        composition: "Рис, нори, угорь, авокадо, соус унаги, кунжут",
        price: 5500,
        weight: 260,
        image: unsplash(SUSHI_IMAGES[2]),
        categorySlug: "sushi",
    },
    {
        name: "Аляска",
        slug: "alyaska",
        description: "Лосось и авокадо в классическом исполнении. Лёгкий и свежий ролл.",
        composition: "Рис, нори, лосось, авокадо, огурец",
        price: 4200,
        weight: 230,
        image: unsplash(SUSHI_IMAGES[3]),
        categorySlug: "sushi",
    },
    {
        name: "Запечённый лосось",
        slug: "zapechennyy-losos",
        description: "Тёплый ролл с запечённым лососем и сырным соусом. Уютный и сытный.",
        composition: "Рис, нори, лосось, сливочный сыр, соус спайси, кунжут",
        price: 5100,
        weight: 250,
        image: unsplash(SUSHI_IMAGES[4]),
        categorySlug: "sushi",
    },
    {
        name: "Темпура ролл",
        slug: "tempura-roll",
        description: "Хрустящая темпура с креветкой внутри — контраст текстур в каждом кусочке.",
        composition: "Рис, нори, креветка темпура, огурец, соус унаги",
        price: 4800,
        weight: 245,
        image: unsplash(SUSHI_IMAGES[5]),
        categorySlug: "sushi",
    },
    {
        name: "Кунсэй",
        slug: "kunsey",
        description: "Обжаренный лосось с зелёным луком. Ароматный ролл с лёгкой копчёностью.",
        composition: "Рис, нори, лосось копчёный, сливочный сыр, зелёный лук",
        price: 4700,
        weight: 235,
        image: unsplash(SUSHI_IMAGES[6]),
        categorySlug: "sushi",
    },
    {
        name: "Сакура",
        slug: "sakura-roll",
        description: "Нежный ролл с тунцом и сливочным сыром. Идеален для первого знакомства с суши.",
        composition: "Рис, нори, тунец, сливочный сыр, огурец, кунжут",
        price: 4600,
        weight: 225,
        image: unsplash(SUSHI_IMAGES[7]),
        categorySlug: "sushi",
    },
    {
        name: "Огурец маки",
        slug: "ogurec-maki",
        description: "Классический вегетарианский маки — свежий огурец и рис в нори.",
        composition: "Рис, нори, огурец, кунжут",
        price: 3200,
        weight: 180,
        image: unsplash(SUSHI_IMAGES[8]),
        categorySlug: "sushi",
    },
    {
        name: "Лосось маки",
        slug: "losos-maki",
        description: "Простой и честный маки с свежим лососем. Любимый базовый ролл.",
        composition: "Рис, нори, лосось",
        price: 3800,
        weight: 190,
        image: unsplash(SUSHI_IMAGES[9]),
        categorySlug: "sushi",
    },
    {
        name: "Унаги ролл",
        slug: "unagi-roll",
        description: "Копчёный угорь с соусом унаги — сладкий и насыщенный вкус.",
        composition: "Рис, нори, угорь, огурец, соус унаги, кунжут",
        price: 5600,
        weight: 255,
        image: unsplash(SUSHI_IMAGES[10]),
        categorySlug: "sushi",
    },
    {
        name: "Спайси тунец",
        slug: "spaysi-tunec",
        description: "Острый тунец со спайси-соусом. Для тех, кто любит пикантность.",
        composition: "Рис, нори, тунец, спайси-соус, огурец, кунжут",
        price: 5200,
        weight: 240,
        image: unsplash(SUSHI_IMAGES[11]),
        categorySlug: "sushi",
    },
    {
        name: "Креветка темпура",
        slug: "krevetka-tempura-roll",
        description: "Хрустящая креветка в темпуре с авокадо — сочный и аппетитный ролл.",
        composition: "Рис, нори, креветка темпура, авокадо, соус спайси",
        price: 5400,
        weight: 250,
        image: unsplash(SUSHI_IMAGES[12]),
        categorySlug: "sushi",
    },
    {
        name: "Веган ролл",
        slug: "vegan-roll",
        description: "Авокадо, огурец и маринованная морковь — свежий ролл без рыбы.",
        composition: "Рис, нори, авокадо, огурец, морковь по-корейски, кунжут",
        price: 3600,
        weight: 200,
        image: unsplash(SUSHI_IMAGES[13]),
        categorySlug: "sushi",
    },
    {
        name: "Филадельфия люкс",
        slug: "filadelfiya-lyuks",
        description: "Двойной лосось и увеличенная порция сыра — для настоящих ценителей.",
        composition: "Рис, нори, лосось, сливочный сыр, огурец, икра тобико",
        price: 5900,
        weight: 270,
        image: unsplash(SUSHI_IMAGES[14]),
        categorySlug: "sushi",
    },
    {
        name: "Канадский",
        slug: "kanadskiy",
        description: "Краб, авокадо и огурец — сбалансированный ролл с нежной текстурой.",
        composition: "Рис, нори, краб, авокадо, огурец, кунжут",
        price: 5300,
        weight: 245,
        image: unsplash(SUSHI_IMAGES[15]),
        categorySlug: "sushi",
    },
    {
        name: "Чикен терiyaki",
        slug: "chicken-teriyaki-roll",
        description: "Курица в соусе терiyaki с овощами — необычный и сытный ролл.",
        composition: "Рис, нори, курица терiyaki, огурец, авокадо, соус унаги",
        price: 4400,
        weight: 235,
        image: unsplash(SUSHI_IMAGES[16]),
        categorySlug: "sushi",
    },
    {
        name: "Сет Классик",
        slug: "set-klassik",
        description: "Набор из 24 штук: Филадельфия, Калифорния и Лосось маки. Идеально на компанию.",
        composition: "Филадельфия ×8, Калифорния ×8, Лосось маки ×8",
        price: 6000,
        weight: 720,
        image: unsplash(SUSHI_IMAGES[17]),
        categorySlug: "sushi",
    },
    {
        name: "Сет Любитель",
        slug: "set-lyubitel",
        description: "20 роллов на выбор шефа — разнообразие вкусов в одной коробке.",
        composition: "Ассорти роллов ×20 (состав уточняется при заказе)",
        price: 5500,
        weight: 650,
        image: unsplash(SUSHI_IMAGES[18]),
        categorySlug: "sushi",
    },
    {
        name: "Онигири лосось",
        slug: "onigiri-losos",
        description: "Японский рисовый треугольник с лососем — удобный перекус на ходу.",
        composition: "Рис, лосось, нори, кунжут, соевый соус",
        price: 3500,
        weight: 160,
        image: unsplash(SUSHI_IMAGES[19]),
        categorySlug: "sushi",
    },

    // ─── Шаурма (20) ──────────────────────────────────────────────────────────
    {
        name: "Классическая шаурма",
        slug: "shaurma-klassicheskaya",
        description: "Курица, свежие овощи и фирменный чесночный соус в тёплом лаваше.",
        composition: "Куриное филе, лаваш, томаты, огурцы, капуста, чесночный соус",
        price: 3200,
        weight: 320,
        image: unsplash(SHAWARMA_IMAGES[0]),
        categorySlug: "shawarma",
    },
    {
        name: "Острая шаурма",
        slug: "shaurma-ostraya",
        description: "Курица со спайси-соусом и перцем — для любителей острого.",
        composition: "Куриное филе, лаваш, овощи, соус спайси, халапеньо",
        price: 3400,
        weight: 330,
        image: unsplash(SHAWARMA_IMAGES[1]),
        categorySlug: "shawarma",
    },
    {
        name: "Шаурма по-еревански",
        slug: "shaurma-po-erevanski",
        description: "Сочная курица, картофель фри внутри и фирменный соус — ереванская классика.",
        composition: "Куриное филе, лаваш, картофель фри, томаты, лук, фирменный соус",
        price: 3600,
        weight: 380,
        image: unsplash(SHAWARMA_IMAGES[2]),
        categorySlug: "shawarma",
    },
    {
        name: "Сырная шаурма",
        slug: "shaurma-syrnaya",
        description: "Расплавленный сыр чеддер и нежная курица — особенно сытная.",
        composition: "Куриное филе, лаваш, сыр чеддер, овощи, соус",
        price: 3500,
        weight: 340,
        image: unsplash(SHAWARMA_IMAGES[3]),
        categorySlug: "shawarma",
    },
    {
        name: "Шаурма BBQ",
        slug: "shaurma-bbq",
        description: "Копчёный соус BBQ и курица на гриле — насыщенный дымный вкус.",
        composition: "Куриное филе, лаваш, соус BBQ, лук, капуста, овощи",
        price: 3300,
        weight: 325,
        image: unsplash(SHAWARMA_IMAGES[4]),
        categorySlug: "shawarma",
    },
    {
        name: "Донер",
        slug: "doner",
        description: "Тонко нарезанное мясо, овощи и йогуртовый соус в лаваше.",
        composition: "Говядина/курица, лаваш, томаты, лук, салат, соус",
        price: 3100,
        weight: 310,
        image: unsplash(SHAWARMA_IMAGES[5]),
        categorySlug: "shawarma",
    },
    {
        name: "Намаз-ан",
        slug: "namaz-an",
        description: "Домашняя шаурма с говядиной и овощами — сытная и ароматная.",
        composition: "Говядина, лаваш, томаты, огурцы, лук, зелень, соус",
        price: 3700,
        weight: 350,
        image: unsplash(SHAWARMA_IMAGES[6]),
        categorySlug: "shawarma",
    },
    {
        name: "Шаурма гриль",
        slug: "shaurma-gril",
        description: "Курица с маринадом на гриле, свежие овощи и лёгкий соус.",
        composition: "Куриное филе гриль, лаваш, перец, томаты, салат, соус",
        price: 3350,
        weight: 315,
        image: unsplash(SHAWARMA_IMAGES[7]),
        categorySlug: "shawarma",
    },
    {
        name: "Шаурма с айраном",
        slug: "shaurma-s-ayranom",
        description: "Классическая шаурма в комплекте с айраном — готовый обед.",
        composition: "Куриное филе, лаваш, овощи, соус, айран 0,3 л",
        price: 3800,
        weight: 400,
        image: unsplash(SHAWARMA_IMAGES[8]),
        categorySlug: "shawarma",
    },
    {
        name: "Детская шаурма",
        slug: "shaurma-detskaya",
        description: "Небольшая порция с мягким вкусом — без острого соуса.",
        composition: "Куриное филе, лаваш, огурец, томаты, лёгкий соус",
        price: 2500,
        weight: 220,
        image: unsplash(SHAWARMA_IMAGES[9]),
        categorySlug: "shawarma",
    },
    {
        name: "Шаурма Бомба",
        slug: "shaurma-bomba",
        description: "Двойное мясо, картофель и сыр — максимально сытный вариант.",
        composition: "Куриное филе ×2, лаваш, картофель фри, сыр, овощи, соус",
        price: 3900,
        weight: 420,
        image: unsplash(SHAWARMA_IMAGES[10]),
        categorySlug: "shawarma",
    },
    {
        name: "Шаурма с овощами гриль",
        slug: "shaurma-ovoshi-gril",
        description: "Курица и овощи на гриле — лёгкая и ароматная шаурма.",
        composition: "Куриное филе, лаваш, перец гриль, баклажан, кабачок, соус",
        price: 3250,
        weight: 330,
        image: unsplash(SHAWARMA_IMAGES[11]),
        categorySlug: "shawarma",
    },
    {
        name: "Чесночная шаурма",
        slug: "shaurma-chesnochnaya",
        description: "Двойной чесночный соус и сочная курица — для настоящих фанатов чеснока.",
        composition: "Куриное филе, лаваш, овощи, чесночный соус ×2",
        price: 3450,
        weight: 335,
        image: unsplash(SHAWARMA_IMAGES[12]),
        categorySlug: "shawarma",
    },
    {
        name: "Халяль шаурма",
        slug: "shaurma-halyal",
        description: "Курица халяль, свежие овощи и натуральный соус без алкоголя.",
        composition: "Куриное филе халяль, лаваш, томаты, огурцы, капуста, соус",
        price: 3150,
        weight: 320,
        image: unsplash(SHAWARMA_IMAGES[13]),
        categorySlug: "shawarma",
    },
    {
        name: "Двойное мясо",
        slug: "shaurma-dvoynoe-myaso",
        description: "Двойная порция мяса в большом лаваше — для самых голодных.",
        composition: "Куриное филе ×2, лаваш, овощи, соус, картофель фри",
        price: 4000,
        weight: 450,
        image: unsplash(SHAWARMA_IMAGES[14]),
        categorySlug: "shawarma",
    },
    {
        name: "Шаурма с соусом тартар",
        slug: "shaurma-tartar",
        description: "Нежный соус тартар и хрустящие овощи — необычное сочетание.",
        composition: "Куриное филе, лаваш, салат, огурцы, соус тартар",
        price: 3550,
        weight: 340,
        image: unsplash(SHAWARMA_IMAGES[15]),
        categorySlug: "shawarma",
    },
    {
        name: "Фалафель",
        slug: "falafel",
        description: "Хрустящий фалафель с овощами и тахini — вегетарианская альтернатива.",
        composition: "Фалафель, лаваш, салат, томаты, огурцы, соус тахini",
        price: 2900,
        weight: 280,
        image: unsplash(SHAWARMA_IMAGES[16]),
        categorySlug: "shawarma",
    },
    {
        name: "Шаурма XL",
        slug: "shaurma-xl",
        description: "Увеличенная порция курицы и овощей — настоящий XL-формат.",
        composition: "Куриное филе, большой лаваш, овощи, картофель фри, соус",
        price: 3750,
        weight: 430,
        image: unsplash(SHAWARMA_IMAGES[17]),
        categorySlug: "shawarma",
    },
    {
        name: "Аджарская шаурма",
        slug: "shaurma-adzharskaya",
        description: "С сыром сулугуни и острым соусом — грузинский акцент в лаваше.",
        composition: "Куриное филе, лаваш, сулугуни, овощи, аджика, соус",
        price: 3400,
        weight: 345,
        image: unsplash(SHAWARMA_IMAGES[18]),
        categorySlug: "shawarma",
    },
    {
        name: "Овощная шаурма",
        slug: "shaurma-ovoshchnaya",
        description: "Гриль-овощи, хумус и зелень — лёгкий вариант без мяса.",
        composition: "Лаваш, баклажан, перец, кабачок, хумус, зелень",
        price: 2800,
        weight: 290,
        image: unsplash(SHAWARMA_IMAGES[19]),
        categorySlug: "shawarma",
    },

    // ─── Напитки (20) ─────────────────────────────────────────────────────────
    {
        name: "Coca-Cola 0,5 л",
        slug: "coca-cola-05",
        description: "Классическая газировка — освежает и идеально сочетается с пиццей.",
        composition: "Coca-Cola, 0,5 л",
        price: 700,
        weight: 500,
        image: unsplash(DRINKS_IMAGES[0]),
        categorySlug: "drinks",
    },
    {
        name: "Coca-Cola Zero 0,5 л",
        slug: "coca-cola-zero-05",
        description: "Вкус Coca-Cola без сахара — для тех, кто следит за калориями.",
        composition: "Coca-Cola Zero, 0,5 л",
        price: 700,
        weight: 500,
        image: unsplash(DRINKS_IMAGES[1]),
        categorySlug: "drinks",
    },
    {
        name: "Fanta 0,5 л",
        slug: "fanta-05",
        description: "Апельсиновая газировка с ярким фруктовым вкусом.",
        composition: "Fanta Orange, 0,5 л",
        price: 700,
        weight: 500,
        image: unsplash(DRINKS_IMAGES[2]),
        categorySlug: "drinks",
    },
    {
        name: "Sprite 0,5 л",
        slug: "sprite-05",
        description: "Лимонно-лаймовая газировка — лёгкая и освежающая.",
        composition: "Sprite, 0,5 л",
        price: 700,
        weight: 500,
        image: unsplash(DRINKS_IMAGES[3]),
        categorySlug: "drinks",
    },
    {
        name: "Jermuk 0,5 л",
        slug: "jermuk-05",
        description: "Армянская минеральная вода из Jermuk — газированная, стекло.",
        composition: "Jermuk, стекло 0,5 л",
        price: 600,
        weight: 500,
        image: unsplash(DRINKS_IMAGES[4]),
        categorySlug: "drinks",
    },
    {
        name: "Bonaqua 0,5 л",
        slug: "bonaqua-05",
        description: "Негазированная вода — чистая и нейтральная.",
        composition: "Bonaqua, 0,5 л",
        price: 600,
        weight: 500,
        image: unsplash(DRINKS_IMAGES[5]),
        categorySlug: "drinks",
    },
    {
        name: "Айран 0,3 л",
        slug: "ayran-03",
        description: "Освежающий кисломолочный напиток — идеален к шаурме и пицце.",
        composition: "Айран, 0,3 л",
        price: 800,
        weight: 300,
        image: unsplash(DRINKS_IMAGES[6]),
        categorySlug: "drinks",
    },
    {
        name: "Лимонад Дюшес",
        slug: "limonad-dushes",
        description: "Грушевый лимонад с ностальгическим вкусом из детства.",
        composition: "Лимонад Дюшес, 0,5 л",
        price: 900,
        weight: 500,
        image: unsplash(DRINKS_IMAGES[7]),
        categorySlug: "drinks",
    },
    {
        name: "Морс клюквенный",
        slug: "mors-klyukva",
        description: "Домашний морс из клюквы — кисло-сладкий и натуральный.",
        composition: "Клюква, сахар, вода, 0,4 л",
        price: 850,
        weight: 400,
        image: unsplash(DRINKS_IMAGES[8]),
        categorySlug: "drinks",
    },
    {
        name: "Лимонад домашний",
        slug: "limonad-domashniy",
        description: "Свежий лимонный лимонад с мятой — готовим каждый день.",
        composition: "Лимон, мята, сахар, газированная вода, 0,4 л",
        price: 1000,
        weight: 400,
        image: unsplash(DRINKS_IMAGES[9]),
        categorySlug: "drinks",
    },
    {
        name: "Ice Tea персик",
        slug: "ice-tea-persik",
        description: "Холодный чай со вкусом персика — лёгкий и ароматный.",
        composition: "Ice Tea Peach, 0,5 л",
        price: 900,
        weight: 500,
        image: unsplash(DRINKS_IMAGES[10]),
        categorySlug: "drinks",
    },
    {
        name: "Red Bull",
        slug: "red-bull",
        description: "Энергетический напиток — бодрит и заряжает.",
        composition: "Red Bull, 0,25 л",
        price: 1200,
        weight: 250,
        image: unsplash(DRINKS_IMAGES[11]),
        categorySlug: "drinks",
    },
    {
        name: "Borjomi 0,5 л",
        slug: "borjomi-05",
        description: "Грузинская лечебно-столовая минеральная вода — знакомый вкус.",
        composition: "Borjomi, 0,5 л",
        price: 1100,
        weight: 500,
        image: unsplash(DRINKS_IMAGES[12]),
        categorySlug: "drinks",
    },
    {
        name: "Сок апельсин",
        slug: "sok-apelsin",
        description: "100% апельсиновый сок — свежий и витаминный.",
        composition: "Апельсиновый сок, 0,3 л",
        price: 950,
        weight: 300,
        image: unsplash(DRINKS_IMAGES[13]),
        categorySlug: "drinks",
    },
    {
        name: "Сок яблоко",
        slug: "sok-yabloko",
        description: "Яблочный сок без добавок — мягкий и натуральный.",
        composition: "Яблочный сок, 0,3 л",
        price: 950,
        weight: 300,
        image: unsplash(DRINKS_IMAGES[14]),
        categorySlug: "drinks",
    },
    {
        name: "Молочный коктейль клубника",
        slug: "kokteyl-klubnika",
        description: "Густой клубничный коктейль — сладкий десерт в стакане.",
        composition: "Молоко, клубника, мороженое, 0,4 л",
        price: 1300,
        weight: 400,
        image: unsplash(DRINKS_IMAGES[15]),
        categorySlug: "drinks",
    },
    {
        name: "Капучино",
        slug: "kapuchino",
        description: "Классический капучино с молочной пенкой — тёплый и бодрящий.",
        composition: "Эспрессо, молоко, 0,25 л",
        price: 1200,
        weight: 250,
        image: unsplash(DRINKS_IMAGES[16]),
        categorySlug: "drinks",
    },
    {
        name: "Эспрессо",
        slug: "espresso",
        description: "Крепкий эспрессо из свежемолотых зёрен — для ценителей кофе.",
        composition: "Эспрессо, 0,06 л",
        price: 600,
        weight: 60,
        image: unsplash(DRINKS_IMAGES[17]),
        categorySlug: "drinks",
    },
    {
        name: "Чай зелёный",
        slug: "chay-zelenyy",
        description: "Ароматный зелёный чай — лёгкий и успокаивающий.",
        composition: "Зелёный чай, 0,4 л",
        price: 700,
        weight: 400,
        image: unsplash(DRINKS_IMAGES[18]),
        categorySlug: "drinks",
    },
    {
        name: "Кисель ягодный",
        slug: "kisel-yagodnyy",
        description: "Густой ягодный кисель — домашний вкус, как у бабушки.",
        composition: "Ягоды, крахмал, сахар, 0,4 л",
        price: 750,
        weight: 400,
        image: unsplash(DRINKS_IMAGES[19]),
        categorySlug: "drinks",
    },

    // ─── Закуски (20) ─────────────────────────────────────────────────────────
    {
        name: "Картофель фри",
        slug: "kartofel-fri",
        description: "Золотистая хрустящая картошка с солью — идеальное дополнение к любому заказу.",
        composition: "Картофель, растительное масло, соль",
        price: 1500,
        weight: 150,
        image: unsplash(SNACKS_IMAGES[0]),
        categorySlug: "snacks",
    },
    {
        name: "Крылья BBQ",
        slug: "krylya-bbq",
        description: "Сочные куриные крылья в соусе BBQ — хрустящие снаружи, нежные внутри.",
        composition: "Куриные крылья, соус BBQ, специи",
        price: 2800,
        weight: 280,
        image: unsplash(SNACKS_IMAGES[1]),
        categorySlug: "snacks",
    },
    {
        name: "Наггетсы",
        slug: "naggetsy",
        description: "Куриные наггетсы в хрустящей панировке с соусом на выбор.",
        composition: "Куриное филе, панировка, масло, соус",
        price: 2200,
        weight: 200,
        image: unsplash(SNACKS_IMAGES[2]),
        categorySlug: "snacks",
    },
    {
        name: "Луковые кольца",
        slug: "lukovye-koltsa",
        description: "Хрустящие кольца лука в панировке — классика к пиву и бургерам.",
        composition: "Лук, панировка, специи, масло",
        price: 1800,
        weight: 160,
        image: unsplash(SNACKS_IMAGES[3]),
        categorySlug: "snacks",
    },
    {
        name: "Моцzarella sticks",
        slug: "mozzarella-sticks",
        description: "Тянущаяся моцzarella в хрустящей корочке — горячая и сырная.",
        composition: "Моцzarella, панировка, маринara-соус",
        price: 2400,
        weight: 180,
        image: unsplash(SNACKS_IMAGES[4]),
        categorySlug: "snacks",
    },
    {
        name: "Сырные шарики",
        slug: "syrnye-shariki",
        description: "Хрустящие шарики с сырной начинкой — удобно делить на компанию.",
        composition: "Сыр чеддер, тесто, панировка, масло",
        price: 2100,
        weight: 170,
        image: unsplash(SNACKS_IMAGES[5]),
        categorySlug: "snacks",
    },
    {
        name: "Хлебные палочки",
        slug: "hlebnye-palochki",
        description: "Чесночные хлебные палочки с соусом — хрустящая закуска к пицце.",
        composition: "Тесто, чеснок, масло, зелень, соус",
        price: 1600,
        weight: 140,
        image: unsplash(SNACKS_IMAGES[6]),
        categorySlug: "snacks",
    },
    {
        name: "Начос с сыром",
        slug: "nachos-s-syrom",
        description: "Хрустящие начos с расплавленным сыром и сalsa — мексиканская классика.",
        composition: "Кукурузные чips, сыр, salsa, jalapeño",
        price: 2500,
        weight: 220,
        image: unsplash(SNACKS_IMAGES[7]),
        categorySlug: "snacks",
    },
    {
        name: "Гренки с чесноком",
        slug: "grenki-chesnok",
        description: "Ароматные гренки с чесночным маслом — просто и очень вкусно.",
        composition: "Багет, чеснок, масло, зелень",
        price: 1700,
        weight: 150,
        image: unsplash(SNACKS_IMAGES[8]),
        categorySlug: "snacks",
    },
    {
        name: "Салат Цезарь",
        slug: "cezar-salat",
        description: "Классический Цезарь с курицей, пармезаном и соусом — свежий и сытный.",
        composition: "Салат рomaine, курица, пармезан, croutons, соус Цезарь",
        price: 2900,
        weight: 250,
        image: unsplash(SNACKS_IMAGES[9]),
        categorySlug: "snacks",
    },
    {
        name: "Греческий салат",
        slug: "grecheskiy-salat",
        description: "Томаты, огурцы, фета и оливки — лёгкий средиземноморский салат.",
        composition: "Томаты, огурцы, перец, фета, оливки, оливковое масло",
        price: 2700,
        weight: 240,
        image: unsplash(SNACKS_IMAGES[10]),
        categorySlug: "snacks",
    },
    {
        name: "Куриный суп",
        slug: "kurinyy-sup",
        description: "Домашний куриный бульон с лапшой — согревает и насыщает.",
        composition: "Курица, лапша, морковь, лук, зелень, 0,4 л",
        price: 2000,
        weight: 400,
        image: unsplash(SNACKS_IMAGES[11]),
        categorySlug: "snacks",
    },
    {
        name: "Картофель по-деревенски",
        slug: "kartofel-derevenskiy",
        description: "Крупные дольки с хрустящей корочкой и специями — сытная закуска.",
        composition: "Картофель, специи, масло, розмарин",
        price: 1900,
        weight: 180,
        image: unsplash(SNACKS_IMAGES[12]),
        categorySlug: "snacks",
    },
    {
        name: "Стрипсы",
        slug: "stripsy",
        description: "Длинные полоски куриного филе в панировке — удобно есть руками.",
        composition: "Куриное филе, панировка, специи, соус",
        price: 2600,
        weight: 210,
        image: unsplash(SNACKS_IMAGES[13]),
        categorySlug: "snacks",
    },
    {
        name: "Чесночный хлеб",
        slug: "chesnochnyy-hleb",
        description: "Тёплый хлеб с чесночным маслом и сыром — ароматная закуска.",
        composition: "Багет, чеснок, масло, сыр моцzarella",
        price: 1650,
        weight: 160,
        image: unsplash(SNACKS_IMAGES[14]),
        categorySlug: "snacks",
    },
    {
        name: "Картофель wedges",
        slug: "kartofel-wedges",
        description: "Картофельные дольки с paprika — хрустящие и ароматные.",
        composition: "Картофель, paprika, масло, соль",
        price: 1850,
        weight: 175,
        image: unsplash(SNACKS_IMAGES[15]),
        categorySlug: "snacks",
    },
    {
        name: "Сырные кубики",
        slug: "syrnye-kubiki",
        description: "Жареные кубики сыra с соусом — горячая закуска к пиву.",
        composition: "Сыр чеддер, панировка, масло, соус",
        price: 2300,
        weight: 165,
        image: unsplash(SNACKS_IMAGES[16]),
        categorySlug: "snacks",
    },
    {
        name: "Креветки темпура",
        slug: "krevetki-tempura-zakuska",
        description: "Крупные креветки в хрустящем кляре — подаём с соусом.",
        composition: "Креветки, темпурный кляр, масло, соус",
        price: 3000,
        weight: 190,
        image: unsplash(SNACKS_IMAGES[17]),
        categorySlug: "snacks",
    },
    {
        name: "Брускetta",
        slug: "bruschetta",
        description: "Хрустящий хлеб с томатами, базиликом и оливковым маслом.",
        composition: "Багет, томаты, базилик, чеснок, оливковое масло",
        price: 2100,
        weight: 170,
        image: unsplash(SNACKS_IMAGES[18]),
        categorySlug: "snacks",
    },
    {
        name: "Сет закусок",
        slug: "set-zakusok",
        description: "Ассорти: фри, наггетсы, кольца лука и соусы — на большую компанию.",
        composition: "Картофель фри, наггетсы, луковые кольца, соусы ×3",
        price: 2950,
        weight: 450,
        image: unsplash(SNACKS_IMAGES[19]),
        categorySlug: "snacks",
    },
];

/** Пиццы с модификаторами «Размер» и «Тесто». */
const PIZZA_MODIFIER_SLUGS = ["pepperoni", "margarita", "chetyre-syra", "myasnaya"] as const;

/** Роллы с модификатором «Порция» (кроме сетов). */
const SUSHI_PORTION_SLUGS = [
    "filadelfiya",
    "kaliforniya",
    "drakon",
    "alyaska",
    "zapechennyy-losos",
    "tempura-roll",
    "kunsey",
    "sakura-roll",
    "ogurec-maki",
    "losos-maki",
    "unagi-roll",
    "spaysi-tunec",
    "krevetka-tempura-roll",
    "vegan-roll",
    "filadelfiya-lyuks",
] as const;

async function addPizzaModifiers(productId: number): Promise<void> {
    await prisma.modifierGroup.create({
        data: {
            productId,
            name: "Размер",
            required: true,
            maxChoices: 1,
            position: 0,
            modifiers: {
                create: [
                    { name: "30 см", priceDelta: 0, position: 0 },
                    { name: "45 см", priceDelta: 2000, position: 1 },
                ],
            },
        },
    });
    await prisma.modifierGroup.create({
        data: {
            productId,
            name: "Тесто",
            required: true,
            maxChoices: 1,
            position: 1,
            modifiers: {
                create: [
                    { name: "Тонкое", priceDelta: 0, position: 0 },
                    { name: "Пышное", priceDelta: 0, position: 1 },
                ],
            },
        },
    });
}

async function addPortionModifier(
    productId: number,
    basePrice: number,
): Promise<void> {
    await prisma.modifierGroup.create({
        data: {
            productId,
            name: "Порция",
            required: true,
            maxChoices: 1,
            position: 0,
            modifiers: {
                create: [
                    { name: "1 шт", priceDelta: 0, position: 0 },
                    {
                        name: "Половина",
                        priceDelta: -Math.round(basePrice * 0.3),
                        position: 1,
                    },
                ],
            },
        },
    });
}

async function main() {
    console.log("🌱 Seeding East West Delivery…");

    // Очистка в порядке зависимостей FK
    await prisma.orderItem.deleteMany();
    await prisma.order.deleteMany();
    await prisma.modifier.deleteMany();
    await prisma.modifierGroup.deleteMany();
    await prisma.product.deleteMany();
    await prisma.category.deleteMany();
    await prisma.promoCode.deleteMany();
    await prisma.deliveryZone.deleteMany();

    const categoriesData = [
        { slug: "pizza", name: "Пицца" },
        { slug: "sushi", name: "Суши и роллы" },
        { slug: "shawarma", name: "Шаурма" },
        { slug: "drinks", name: "Напитки" },
        { slug: "snacks", name: "Закуски" },
    ] as const;

    const categories = await Promise.all(
        categoriesData.map((c, position) =>
            prisma.category.create({
                data: {
                    name: c.name,
                    slug: c.slug,
                    position,
                    isActive: true,
                },
            }),
        ),
    );

    const categoryIdBySlug = Object.fromEntries(
        categories.map((c) => [c.slug, c.id] as const),
    ) as Record<(typeof categoriesData)[number]["slug"], number>;

    if (productsData.length !== 100) {
        throw new Error(
            `Expected 100 products, got ${productsData.length}`,
        );
    }

    const productIdBySlug = new Map<string, number>();
    const productPriceBySlug = new Map<string, number>();

    for (const p of productsData) {
        const images = [p.image] as Prisma.InputJsonArray;
        const created = await prisma.product.create({
            data: {
                name: p.name,
                slug: p.slug,
                description: p.description,
                composition: p.composition,
                price: p.price,
                weight: p.weight,
                images,
                mainImage: p.image,
                isActive: true,
                categoryId: categoryIdBySlug[p.categorySlug],
            },
        });
        productIdBySlug.set(p.slug, created.id);
        productPriceBySlug.set(p.slug, p.price);
    }

    for (const slug of PIZZA_MODIFIER_SLUGS) {
        const productId = productIdBySlug.get(slug);
        if (productId != null) {
            await addPizzaModifiers(productId);
        }
    }

    for (const slug of SUSHI_PORTION_SLUGS) {
        const productId = productIdBySlug.get(slug);
        const price = productPriceBySlug.get(slug);
        if (productId != null && price != null) {
            await addPortionModifier(productId, price);
        }
    }

    await prisma.promoCode.create({
        data: {
            code: "WELCOME",
            discountType: "PERCENTAGE",
            discountValue: 10,
            isActive: true,
        },
    });

    await prisma.deliveryZone.createMany({
        data: deliveryZonesData.map((z) => ({
            ...z,
            isActive: true,
        })),
    });

    console.log(`✅ Категорий: ${categories.length}`);
    console.log(`✅ Товаров: ${productsData.length}`);
    console.log(`✅ Зоны доставки: ${deliveryZonesData.length}`);
    console.log("✅ Seeding completed.");
}

main()
    .catch((e) => {
        console.error("❌ Seeding error:", e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });
